language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
cache: cargo

before_script:
  - rustup component add clippy rustfmt

script:
  - cargo update
  - cargo check
  - cargo test